cask "google-chrome"
cask "discord"
cask "bitwarden"
cask "notion"
cask "vlc"

cask "stats"

brew "doctl"
brew "scrcpy"

tap "homebrew/cask-versions"
cask "temurin8"
cask "temurin11"


mas "Todoist", id: 585829637
# cask? openjdk@17