cask "google-chrome"
cask "discord"
cask "bitwarden"
cask "notion"
cask "vlc"

cask "stats"

cask "orbstack"

# brew "doctl"
brew "scrcpy"
brew "flyctl"

# tap "homebrew/cask-versions"
# cask "temurin8"
# cask "temurin11"

# tap "depot/tap"
# brew "depot"

# cask "google-cloud-sdk"

mas "Todoist", id: 585829637
# cask? openjdk@17