brew "awscli"
mas "Slack", id: 803453959

# brew "k9s", args: ["build-from-source", "force"]
# cask "openlens"
# brew "blackbox"
brew "pre-commit"
brew "terraform-docs"
# brew "oath-toolkit"
# brew "orka"

# tap "kreuzwerker/taps"
# brew "m1-terraform-provider-helper"

# brew "docker-credential-helper-ecr"

# cask "1password/tap/1password-cli"
# brew "k9s", args: ["build-from-source"]
# brew "sops"
# brew "krew"

# brew "pgbadger"
brew "steampipe"
brew "turbot/tap/powerpipe"
# brew "vale"
brew "duckdb"

cask "session-manager-plugin"

brew "cloudflared"
tap "stripe/stripe-cli"
brew "stripe/stripe-cli/stripe"

brew "gnupg"
tap "dopplerhq/cli"
brew "dopplerhq/cli/doppler"

brew "gh"