brew "awscli"
mas "Slack", id: 803453959
cask "zoom"

brew "k9s"
cask "openlens"
brew "blackbox"
brew "pre-commit"
brew "terraform-docs"
brew "oath-toolkit"

tap "kreuzwerker/taps"
brew "m1-terraform-provider-helper"

brew "docker-credential-helper-ecr"
