brew "awscli"
mas "Slack", id: 803453959

# brew "k9s", args: ["build-from-source", "force"]
cask "openlens"
brew "blackbox"
brew "sops"
brew "pre-commit"
brew "terraform-docs"
brew "oath-toolkit"

tap "kreuzwerker/taps"
brew "m1-terraform-provider-helper"

brew "docker-credential-helper-ecr"

cask "1password/tap/1password-cli"

tap "int128/kubelogin"
brew "kubelogin"

brew "pgbadger"
brew "jfrog-cli"