apiVersion: v1
kind: Pod
metadata:
  name: mkuntz-debug
  annotations:
    appmesh.k8s.aws/sidecarInjectorWebhook: disabled
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 2
  securityContext:
    runAsUser: 1000
  # nodeSelector:
  #   cicd: "true"
  # tolerations:
  #   - key: "dedicated"
  #     operator: "Equal"
  #     value: "cicd"
  #     effect: "NoSchedule"
  containers:
    - name: nix
      image: nicolaka/netshoot
      # image: docker:dind
      stdin: true
      tty: true
      command: ["/bin/sh"]
      args: ["-c", "while sleep 3600; do :; done"]
      # args: ["-c", "apk add curl bash; while sleep 3600; do :; done"]
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        seccompProfile:
          type: "RuntimeDefault"
        capabilities: 
          drop: ["ALL"]
          
      resources:
        limits:
          cpu: "0.25"
          memory: "500Mi"
        requests:
          cpu: "0.25"
          memory: "500Mi"